[package]
name = "rushlog"
version = "0.1.0"
authors = ["Guillaume Charmetant <gcharmetant@tea-ebook.com>"]

[dependencies.iron]
version = "*"

[dependencies.log]
version = "*"
[dependencies.env_logger]
version = "*"

[dependencies.time]
version = "*"
